# Generated by Django 6.0.6 on 2026-06-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdata_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
