# Generated by Django 6.0.6 on 2026-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pdesc', models.CharField(max_length=100)),
                ('price', models.CharField()),
                ('category', models.CharField(max_length=100)),
                ('trending', models.BooleanField(default=False)),
                ('offer', models.BooleanField(default=False)),
                ('pimg', models.ImageField(default='default.webp', upload_to='uploads/')),
            ],
        ),
    ]
