# Generated by Django 6.0.6 on 2026-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
