# Generated by Django 6.0.6 on 2026-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_details_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='pname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total',
            field=models.IntegerField(),
        ),
    ]
