# Generated by Django 6.0.6 on 2026-06-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_order_details_name_alter_order_details_pname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
